# Initialisation
autoload -U colors && colors
lip() { ip=$(ifconfig 2>/dev/null | grep -oE 'inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | awk '{print $2}' | grep -v '^127\.' | tail -n1); echo "$ip"; }
PS1="%B%{$fg[white]%}[%{$fg[white]%}%n%{$fg[white]%}@%{$fg[white]%}MacBook:%{$fg[white]%}$(lip)%{$fg[white]%} %{$fg[cyan]%}%~%{$fg[white]%}]%{$reset_color%}$%b "

# Options
setopt share_history
setopt append_history
setopt hist_ignore_dups
setopt autocd

# History
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.histfile
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=''

# System
alias clear="printf '\33c\e[3J'"
alias copy="pbcopy <"
alias delete="trash -v -F"
alias pwd="pwd -P"
alias headless="sudo pmset -a disablesleep 1 && pmset displaysleepnow"
alias normal="sudo pmset -a disablesleep 0"

# Homebrew
alias install="brew install"
alias remove="brew uninstall"
alias update="source ~/.zshrc && brew update && brew upgrade && brew upgrade --cask --greedy && source ~/.zshrc"
alias clean="source ~/.zshrc && brew autoremove && brew cleanup --scrub && brew services cleanup && brew doctor && source ~/.zshrc && bash /usr/local/bin/UpdateAria2.sh && sudo rm -rf /Users/shashank/Library/Preferences/com.adobe.Acrobat.Pro.plist /Users/shashank/Movies/TV /Users/shashank/Music/Music"
alias search="brew search"
alias list="brew leaves && brew list --cask"

# Development 
alias gitall="git add . && git commit -m 'Changes made' && git push origin main"
alias download="aria2c"
reset() {
  : > ~/.histfile
  cat >> ~/.histfile <<'EOF'
source ~/.zshrc
update && clean
list
fastfetch
clear
EOF
}
alias get="sudo bash /usr/local/bin/get.sh"
alias send="sudo bash /usr/local/bin/send.sh"
#alias aria2++="bash /usr/local/bin/UpdateAria2.sh"

# Environment Variables
export EDITOR="nvim"
export VISUAL="nvim"

# LF to Switch Directories
lfcd () {
    tmp="$(mktemp -uq)"
    trap "rm -f $tmp >/dev/null 2>&1 && trap - HUP INT QUIT TERM EXIT" HUP INT QUIT TERM EXIT
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}

# Key Bindings
bindkey "^[[1;3D" backward-word              # option + ←
bindkey "^[[1;3C" forward-word               # option + →
bindkey "^A" beginning-of-line               # control + a
bindkey "^L" end-of-line                     # control + l
bindkey -s "^o" "^ulfcd\n"                   # control + o
bindkey '^[[A' history-substring-search-up   # ↑
bindkey '^[[B' history-substring-search-down # ↓

# Plugins
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
